<?xml version="1.0" encoding="windows-1252"?>
<definitions xmlns:SOAP-ENV="http://schemas.xmlsoap.org/soap/envelope/" xmlns:xsd="http://www.w3.org/2001/XMLSchema" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xmlns:SOAP-ENC="http://schemas.xmlsoap.org/soap/encoding/" xmlns:tns="urn:transacciones" xmlns:soap="http://schemas.xmlsoap.org/wsdl/soap/" xmlns:wsdl="http://schemas.xmlsoap.org/wsdl/" xmlns="http://schemas.xmlsoap.org/wsdl/" targetNamespace="urn:transacciones">
<types>
<xsd:schema targetNamespace="urn:transacciones">
 <xsd:import namespace="http://schemas.xmlsoap.org/soap/encoding/"/>
 <xsd:import namespace="http://schemas.xmlsoap.org/wsdl/"/>
</xsd:schema>
</types>
<message name="fnGenericaRequest">
  <part name="codOperacion" type="xsd:string"/>
  <part name="nombre" type="xsd:string"/>
  <part name="email" type="xsd:string"/>
  <part name="numControl" type="xsd:string"/>
  <part name="monto" type="xsd:string"/>
  <part name="idVirtualPoint" type="xsd:string"/>
  <part name="duracionOperaciones" type="xsd:string"/>
  <part name="idUsuario" type="xsd:string"/>
  <part name="idCliente" type="xsd:string"/>
  <part name="hashValidate" type="xsd:string"/></message>
<message name="fnGenericaResponse">
  <part name="return" type="xsd:string"/></message>
<portType name="transaccionesPortType">
  <operation name="fnGenerica">
    <documentation>Este WebService permite registrar una transaccion en el sistema.</documentation>
    <input message="tns:fnGenericaRequest"/>
    <output message="tns:fnGenericaResponse"/>
  </operation>
</portType>
<binding name="transaccionesBinding" type="tns:transaccionesPortType">
  <soap:binding style="rpc" transport="http://schemas.xmlsoap.org/soap/http"/>
  <operation name="fnGenerica">
    <soap:operation soapAction="urn:transacciones#fnGenerica" style="rpc"/>
    <input><soap:body use="encoded" namespace="urn:transacciones" encodingStyle="http://schemas.xmlsoap.org/soap/encoding/"/></input>
    <output><soap:body use="encoded" namespace="urn:transacciones" encodingStyle="http://schemas.xmlsoap.org/soap/encoding/"/></output>
  </operation>
</binding>
<service name="transacciones">
  <port name="transaccionesPort" binding="tns:transaccionesBinding">
    <soap:address location="http://localhost/r1i2n3g4Central/webservices/server/transacciones.php"/>
  </port>
</service>
</definitions>